sudo: required
language: cpp

branches:
  only:
   - develop

matrix:
  include:
    # clang-3.5 (Ubuntu)
    - env: CLANG_VERSION=3.5
      compiler: clang
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - clang-3.5
            - libc++-dev
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}" CXXFLAGS="-stdlib=libc++"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ls
  - ./runUnitTests

notifications:
  email: false
