sudo: required
dist: precise
language: cpp

branches:
  only:
   - develop

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./runUnitTests
