sudo: required
dist: precise
language: cpp

branches:
  only:
   - develop

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install cmake
script:
  - cmake && make
  - ./runUnitTests
